const municipioFields = [
  //Definindo as propriedades do geojson do polígono do município
  {name: 'nome', position: 0, type: 'string'},
  {name: 'área', position: 1, type: 'float'},
  {name: 'população', position: 2, type: 'integer'}
];
const pontosFields = [
  
  //Definindo os filtros do Buscador
  {name:'Data do Acidente', position: 0, type: 'date'},
  {name:'Dia do Acidente', position: 1, type: 'integer'},
  {name:'Mês do Acidente', position: 2, type: 'string'},
  {name:'Ano do Acidente', position: 3, type: 'integer'},
  {name:'Ano/Mês do Acidente', position: 4, type: 'integer'},
  {name:'Dia da Semana', position: 5, type: 'string'},
  {name:'Hora do Acidente', position: 6, type: 'float'},
  {name:'Turno', position: 7, type: 'string'},
  {name:'Batalhão de Trânsito', position: 8, type: ''},
  {name:'Companhia de Trânsito', position: 9, type: ''},
  {name:'Região Administrativa', position: 10, type: 'string'},
  {name:'Logradouro', position: 11, type: 'string'},
  {name:'Número/Km', position: 12, type: 'integer'},
  {name:'Jurisdição', position: 13, type: 'string'},
  {name:'Administração', position: 14, type: 'string'},
  {name:'Conservação', position: 15, type: 'string'},
  {name:'Condições Climáticas', position: 16, type: 'string'},
  {name:'Iluminação', position: 17, type: 'string'},
  {name:'Mão de Direção', position: 18, type: 'string'},
  {name:'Obras na Pista', position: 19, type: 'string'},
  {name:'Relevo', position: 20, type: 'string'},
  {name:'Superfície da Via', position: 21, type: 'string'},
  {name:'Tipo de Pavimento', position: 22, type: 'string'},
  {name:'Tipo de Pista', position: 23, type: 'string'},
  {name:'Traçado', position: 24, type: 'string'},
  {name:'Veículos Envolvidos - Bicicleta', position: 25, type: 'integer'},
  {name:'Veículos Envolvidos - Caminhão', position: 26, type: 'integer'},
  {name:'Veículos Envolvidos - Automóvel', position: 27, type: 'integer'},
  {name:'Veículos Envolvidos - Motocicleta', position: 28, type: 'integer'},
  {name:'Veículos Envolvidos - Ônibus', position: 29, type: 'integer'},
  {name:'Veículos Envolvidos - Pedestres', position: 30, type: 'integer'},
  {name:'Pessoas Envolvidas - Grave', position: 31, type: 'integer'},
  {name:'Pessoas Envolvidas - Ileso', position: 32, type: 'integer'},
  {name:'Pessoas Envolvidas - Leve', position: 33, type: 'integer'},
  {name:'Serviço de Atendimento - Bombeiro', position: 34, type: 'string'},
  {name:'Serviço de Atendimento - PMRV', position: 35, type: 'string'},
  {name:'Serviço de Atendimento - PRF', position: 36, type: 'string'},
  {name:'Serviço de Atendimento - Rádio Patrulha', position: 37, type: 'string'},
  {name:'Serviço de Atendimento - CPTRAN', position: 38, type: 'string'},
  {name:'Tipo de Via', position: 39, type: 'string'},
  {name:'Tipo de Acidente - Atropelamento (Pedestre)', position: 40, type: 'integer'},
  {name:'Tipo de Acidente - Atropelamento (Animal)', position: 41, type: 'integer'},
  {name:'Tipo de Acidente - Choque', position: 42, type: 'integer'},
  {name:'Tipo de Acidente - Colisão ', position: 43, type: 'integer'},
  {name:'Tipo de Acidente - Outros tipos de Acidente', position: 44, type: 'integer'},
  {name:'Turno + Dia de Semana', position: 45, type: 'string'},
];
